# Generated by Django 4.1.1 on 2022-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmodel",
            name="cabinet_number",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="campus",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="pair_number",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="pair_time_end",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="pair_time_start",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="pair_type",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="subject_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="teacher_name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="week_day",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="week_parity",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
