# Generated by Django 4.1.1 on 2022-12-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0002_groupmodel_cabinet_number_groupmodel_campus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.TextField(null=True)),
                ("pair_time_start", models.CharField(max_length=8, null=True)),
                ("pair_time_end", models.CharField(max_length=8, null=True)),
                ("pair_number", models.SmallIntegerField(null=True)),
                ("pair_type", models.CharField(max_length=32, null=True)),
                ("teacher_name", models.CharField(max_length=32, null=True)),
                ("cabinet_number", models.CharField(max_length=16, null=True)),
                ("campus", models.CharField(max_length=16, null=True)),
                ("week_parity", models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="groupmodel", name="cabinet_number",),
        migrations.RemoveField(model_name="groupmodel", name="campus",),
        migrations.RemoveField(model_name="groupmodel", name="pair_number",),
        migrations.RemoveField(model_name="groupmodel", name="pair_time_end",),
        migrations.RemoveField(model_name="groupmodel", name="pair_time_start",),
        migrations.RemoveField(model_name="groupmodel", name="pair_type",),
        migrations.RemoveField(model_name="groupmodel", name="subject_name",),
        migrations.RemoveField(model_name="groupmodel", name="teacher_name",),
        migrations.RemoveField(model_name="groupmodel", name="week_day",),
        migrations.RemoveField(model_name="groupmodel", name="week_parity",),
        migrations.CreateModel(
            name="DayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_day", models.CharField(max_length=16, null=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_app.pairmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="day",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule_app.daymodel",
            ),
            preserve_default=False,
        ),
    ]
