# Generated by Django 4.1.1 on 2022-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0004_remove_daymodel_pair_daymodel_pair"),
    ]

    operations = [
        migrations.RemoveField(model_name="groupmodel", name="day",),
        migrations.AddField(
            model_name="groupmodel",
            name="day_info",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="DayModel",),
        migrations.DeleteModel(name="PairModel",),
    ]
